### PR TITLE
BREAKING: Docker revision - Clean up dockerfile with comments

### PR DESCRIPTION
**Pull request by shleeable**
# BREAKING CHANGES:
1. Move default image tool from `gd` to `imagick`.
2. Move redis driver from `predis` to `phpredis`.

--

Apache has almost been tested. I need to test and confirm the upgrade flow
We need to figure out a stable config for nginx.

fpm has never worked for me correctly as it currently is designed. I'm going to rebuild it after this is merged.

### Installation steps:
Confirm the .env.docker is setup correctly

> Setup nginx reverse proxy
docker-compose up -d postgres keydb
docker-compose run --rm app php artisan key:generate
docker-compose run --rm app php artisan passport:keys
docker-compose run --rm app php artisan migrate
docker-compose run --rm app php artisan horizon:install
docker-compose run --rm app php artisan import:cities
docker-compose up -d

docker-compose build --pull
docker-compose down app worker
docker-compose run --rm app php artisan migrate
docker-compose up -d

### CODE REVIEW

**Comment by shleeable** [comment]
@dansup I want to confirm this is ready on a new instance.

**Comment by dansup** [comment]
@shleeable is this ready to merge?

**Comment by shleeable** [comment]
@dansup this is ready to be merged as is. but just make people aware this is a massive breaking change

**Comment by shleeable** [comment]
crontab for 
`* * * * * cd /path-to-your-project && docker-compose run --rm app php artisan schedule:run >> /dev/null 2>&1`

**Comment by dansup** [comment]
@shleeable Perfect, made an [announcement](https://mastodon.social/@pixeldev/103779020027459288) which should give instances enough time to prepare for the update!

**Comment by Strubbl** [comment]
maybe you want to try a docker linter like https://github.com/hadolint/hadolint

**Comment by shleeable** [comment]
```
/dev/stdin:15 DL3009 Delete the apt-get lists after installing something
/dev/stdin:18 DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
/dev/stdin:19 DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
/dev/stdin:51 DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
/dev/stdin:61 SC2046 Quote this to prevent word splitting.
/dev/stdin:68 DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
/dev/stdin:73 SC2046 Quote this to prevent word splitting.
/dev/stdin:105 DL3025 Use arguments JSON notation for CMD and ENTRYPOINT arguments
```

fixed some of those. the package version won't be pinned.
and the first one is done at the end, just not after every apt-get install.

**Pull request closed without merging**
