### PR TITLE
Rename filters

### PR DESCRIPTION
**Pull request by snan**
New names for the filters. Keep on tweaking 'em if you don't like them, I just pulled them out of a hat 🤷🏻‍♀️

### CODE REVIEW

**Comment by bunnybones1** [comment]
Ludwig should be renamed to Beethoven

**Comment by snan** [comment]
> Ludwig should be renamed to Beethoven

That's fine by me. I thought it might be a li'l on the nose so I went with Wendy as per https://en.wikipedia.org/wiki/Koopalings

**Comment by juliloving** [comment]
1977 should be renamed to Orwell (because 1984 the book)

**Comment by snan** [comment]
> 1977 should be renamed to Orwell (because 1984 the book)

That's fine by me. I was thinking that was a bit unappealing/boot-in-face-y for a photo-beautifier. So I turned to [this 1977 movie character](https://en.wikipedia.org/wiki/Luke_Skywalker).

Ultimately if people wanna bikeshed about this then IDC. I'll unsubscribe and this'll just be a drive by contribution. That's fine too. 🤷🏻‍♀️
I haven't heard anything from the Pixelfed team.

**Comment by juliloving** [comment]
I didn't know Luke was a reference to anything, sorry :)

I hope team pixelfed responds because the issue at hand (legal matter) is a big deal

**Comment by floscher** [comment]
The maintainers came up with another set of changes to the filters: https://mastodon.social/@dansup/109605006708970886

**Comment by snan** [comment]
Obviously the names selected by team members are what you're gonna go with and that's fine, that's a good idea, so I'll close the PR.

But referring to that as "already on the way" is misleading and dishonest and cruel since I submitted this way before.🤬 I submitted this PR just hours after the i1977,  iAdon, iAmaro version was published.

**Comment by floscher** [comment]
I'm sorry if this came across as rude. I have no affiliation with the project and just stumbled on that post, so I thought I'd let you know, since it seemed you were unaware.

It was just meant as a factual description that the post sounds like the changes would go live within a few hours. Should have worded that better.

**Pull request closed without merging**
