### PR TITLE
Add description for visually impaired field

### PR DESCRIPTION
**Pull request by mkljczk**
It does not federate, so a bit work-in-progress. I don't know php and activitypub enough to take care of this…
#117 
alt

### CODE REVIEW

**Comment by andriussev** [comment]
Pardon my ignorance, but considering that it is an image sharing platform, how does supporting visually impaired people help the cause?

Apart from that, it's unclear how descriptions should be handled.

Please fix the validation rule: https://github.com/dansup/pixelfed/pull/124/files#diff-cd8487f20fdf44ab25f3701e48fab225R35

**Comment by ghost** [comment]
@andriussev This is also a federated platform, and presumably images will be shared outside of the initial platform, off pixelfed and onto text-based platforms like Mastodon. In addition, some people are only partially visually impaired and not completely blind (see: literally everyone who needs visual aids like glasses) and it may be helpful for them to have text that can be read via screen reader even though they can still partially see the image being shared. Also sometimes images are just busy and it's hard to see what's going on, but text might help clarify.

**Comment by ghost** [comment]
Also, accessibility always helps a cause.

**Comment by ghost** [comment]
Hey, a friend said 
>"i think masto federates image descriptions by including them in the name field of the Attachment"

Hopefully that's helpful!!

**Comment by vilbi** [comment]
As I als user understand the federated concept, the image discription is realized via the alt image text like described here https://en.wikipedia.org/wiki/Alt_attribute?wprov=sfla1
As a quick fix, the post text can be placed there.

**Comment by mkljczk** [comment]
@vilbi, that’s what the PR is doing right now

**Comment by dansup** [comment]
@m4sk1n I think this is an important accessibility requirement, I will work on updating this merge request!

**Comment by vilbi** [comment]
Thanks!

**Comment by dansup** [comment]
Added in #410, the main difference between this PR and #410 is that its possible to set a caption for each photo instead of a single caption for every photo.

**Pull request closed without merging**
