### PR TITLE
Update Dockerfile.fpm and Dockerfile.apache to php-8-1, plus other cleanup.

### PR DESCRIPTION
**Pull request by bplein**
Update both Dockerfiles to php-8.1, clean up old breakage in Dockerfile.fpm pertaining to an unused package, and making sure the two dockerfiles match everywhere except as it pertains to apache directives.

These edits to staging build without error.

### CODE REVIEW

**Comment by M-D-M** [comment]
Confirmed -- I was able to build the pixelfed image finally using your staging branch.  If I can get pixelfed booted, I'll add a review.

**Comment by M-D-M** [comment]
One issue I've found -- the dockerfile, when booted, doesn't run "php artisan key:generate" -- I guess we need some sort of init file that'll run this if it's a new container, or is everyone just running this manually?

**Comment by bplein** [comment]
I actually haven't installed pixelfed yet because I will only run it if it has a docker image 😀 Do I decided to contribute to get it done.

**Comment by M-D-M** [comment]
> I actually haven't installed pixelfed yet because I will only run it if it has a docker image 😀 Do I decided to contribute to get it done.


Well, if you fixed it this much without even using it, very impressive.  I can confirm it boots with docker now, and I'm working on what needs to be done after that first boot.

**Comment by bplein** [comment]
> Well, if you fixed it this much without even using it, very impressive. I can confirm it boots with docker now, and I'm working on what needs to be done after that first boot.

Thanks. I run my own Mastodon instance and I’ve been working on a simplified container install for that as well (but in that case I run it and know how to test it quickly) 

I won’t get to it until later in the week but I’ll start using this image and working on “first run” docs as well.

**Comment by recklessop** [comment]
This helped me get the containers built too. Thanks!

**Comment by ambiamber** [comment]
bplein:staging is 166 commits behind pixelfed:staging
Do you think maybe doing a refresh would be cool? git stash and so on?

**Comment by bplein** [comment]
> bplein:staging is 166 commits behind pixelfed:staging
> Do you think maybe doing a refresh would be cool? git stash and so on?

I think it's good now. I'm a git novice...

**Comment by ambiamber** [comment]
I think I've found out why this PR is not being merged:
https://github.com/pixelfed/pixelfed/pull/3735/files
Basically you have to PR against dev not staging.
https://en.wikipedia.org/wiki/Deployment_environment

**Comment by Strubbl** [comment]
> I think I've found out why this PR is not being merged: https://github.com/pixelfed/pixelfed/pull/3735/files Basically you have to PR against dev not staging. https://en.wikipedia.org/wiki/Deployment_environment

no, staging is the the target branch, see https://github.com/pixelfed/pixelfed/blob/dev/CONTRIBUTING.md#branches

**Comment by bplein** [comment]
At first glance, the PR that @osresearch has submitted is worthy for cleaning up the bootstrap and putting they into the dockerfile or a first run script. But it (and other PRs) mostly seem to be contributing to Apache. If you can get the other contributor to move their PR to staging, and if it works and is accepted, I can rework mine based on the new staging.

**Comment by bplein** [comment]
I'm looking at the e dockerfiles in staging and see https://github.com/pixelfed/pixelfed/blob/bce1d547e7366c2fe509107dc2e70f515dc2c78b/contrib/docker/Dockerfile.apache#L93

This looks like a workaround for data and code being mixed in the same volume. That is a bad practice, and any fix would come from outside of the dockerfile. 

The project should have uploads in a distinct folder with no code. Other things that the end user admin may want to change like config files should be either in a volume or if they are optional then they can be mapped in singly.  

This way we aren't dragging the whole repo into the image. 

I am going to get a basic system installed this weekend to see if (a) I'm going to run pixelfed and (b) if I can contribute to untangling the data from the code (I am not sure that it's entangled. But the comment in the code suggests that it is.)

**Comment by ambiamber** [comment]
I got Pixelfed running on Fedora rawhide in rootless podman yesterday but I used code from #2137 not this.

**Comment by Strubbl** [comment]
> I got Pixelfed running on Fedora rawhide in rootless podman yesterday but I used code from #2137 not this.

This is the setup i am running, too. I only changed the base image to `php:8-apache-bullseye` only locally on my machine to not open another PR w.r.t docker.

**Comment by ambiamber** [comment]
> > I got Pixelfed running on Fedora rawhide in rootless podman yesterday but I used code from #2137 not this.
> 
> This is the setup i am running, too. I only changed the base image to `php:8-apache-bullseye` only locally on my machine to not open another PR w.r.t docker.

Can you please share your `docker-compose.yml` file that you use for rootless podman (on a gist or something) please?

**Comment by Strubbl** [comment]
> Can you please share your `docker-compose.yml` file that you use for rootless podman (on a gist or something) please?

I do not use podman. Only `docker-compose up`. My changes to `docker-compose.yml` are only w.r.t. the port i am binding the app to and for the volumes, which are saved in a folder. So pretty boring:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 5b342f19..4efb759d 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -29,7 +29,7 @@ services:
       - external
       - internal
     ports:
-      - "8080:80"
+      - "127.0.0.1:3012:80"
     depends_on:
       - db
       - redis
@@ -77,9 +77,25 @@ services:
 
 volumes:
   db-data:
+    driver_opts:
+      type: none
+      o: bind
+      device: /data/pixelfed/mysql
   redis-data:
+    driver_opts:
+      type: none
+      o: bind
+      device: /data/pixelfed/redis
   app-storage:
+    driver_opts:
+      type: none
+      o: bind
+      device: /data/pixelfed/app
   app-bootstrap:
+    driver_opts:
+      type: none
+      o: bind
+      device: /data/pixelfed/bootstrap
```

**Comment by ambiamber** [comment]
Sorry @Strubbl I misinterpreted what you meant by _"This is the setup i am running, too."_
I also meant I'm using parts of #3735 not this PR and not #2137 to do pixelfed in rootless podman.

**Comment by harmtemolder** [comment]
It looks like this is already being worked on as part of #4050

**Comment by dansup** [comment]
Fixed in #4050

**Pull request closed without merging**
