### PR TITLE
[CSS] Small minor graphic bug

### PR DESCRIPTION
**Pull request by StefOfficiel**
.card-img-top border top left & right
Before : 

After :

### CODE REVIEW

**Review by dansup — CHANGES_REQUESTED** [review]
Please do not make changes to compiled CSS as they will be gone the next time assets are compiled by webpack.

You can find the sass/js files in resources/assets/

**Comment by StefOfficiel** [comment]
Oh, sorry !

**Comment by dansup** [comment]
@StefOfficiel No worries! Can you please move the changes to the bottom of the [custom.scss](https://github.com/pixelfed/pixelfed/blob/dev/resources/assets/sass/custom.scss#L310) file?

**Comment by dansup** [comment]
@StefOfficiel I am going to close this PR for now, feel free to ping me when you update the custom.scss and remove the compiled assets from this PR.

**Pull request closed without merging**
