### PR TITLE
Update register.blade.php

### LINKED ISSUE #3811: Update register page to match login page
My changes to the login page was accepted awhile back so will submit one for register page

Here is what it looks like currently

pixelfedregistercurrent

### PR DESCRIPTION
**Pull request by okpierre**
Minor adjustments to fix https://github.com/pixelfed/pixelfed/issues/3811

See screen shot

pixelfedregisterpage

### CODE REVIEW

**Comment by dansup** [comment]
Please rebase against the staging branch!

**Comment by okpierre** [comment]
@dansup done

**Comment by mryoaz** [comment]
@okpierre Maybe an idea to also fix issue #1621 in this PR?
Or must that be done in an other PR?

**Comment by svenluijten** [comment]
Removing the `<label>` elements entirely is a pretty big accessibility faux-pas. The labels didn't have `for` attributes to begin with, but they absolutely deserve to be there, even if only for screen-reader software. 

An alternative would be to add [`aria-label` attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) to all of the `<input>` elements so that this page can still be used by people using assistive technology to use Pixelfed.

**Comment by okpierre** [comment]
@svenluijten Thanks for your input. Updated with aria-label. Let me know if I missed anything.

**Comment by mitexleo** [comment]
I think old one looks better...

**Comment by svenluijten** [comment]
@okpierre wouldn't it make sense to use the translation strings (`__('...')`) for the labels? That's what the placeholders are using. Also, the `<button>` element doesn't _need_ an `aria-label` attribute. From the page I linked above:

> By default, a button's accessible name is the content between the opening and closing `<button>` tags, an image's accessible name is the content of its `alt` attribute, and a form input's accessible name is the content of the associated `<label>` element.

As an aside, I've submitted a PR to fix this in all authentication views: https://github.com/pixelfed/pixelfed/pull/3980.

**Comment by ThisIsMissEm** [comment]
@dansup I think you're redoing this screen or have redone it, so perhaps this needs to be closed?

**Comment by dansup** [comment]
> @dansup I think you're redoing this screen or have redone it, so perhaps this needs to be closed?

Yes, I'm working on a whole new registration flow which isn't compatible with these changes, we appreciate your contribution though!

**Pull request closed without merging**
