### PR TITLE
ES Lint errors fixes and code formatting

### PR DESCRIPTION
**Pull request by KirankumarAmbati**
**Note:** Not a breaking changes. These changes are fixes for ESLint errors and bit of code formatting

### CODE REVIEW

**Comment by KirankumarAmbati** [comment]
**CC:** @dansup

**Comment by dansup** [comment]
@KirankumarAmbati This conflicts with a few components that haven't been pushed yet.

**Comment by KirankumarAmbati** [comment]
Can we do this once those changes are pushed  ? I believe some of this changes will increase performance like adding key attribute to elements iterating in a loop.

**Comment by dansup** [comment]
@KirankumarAmbati Yes, I hope to have them ready next week and will ping you!

**Comment by KirankumarAmbati** [comment]
Sure 👍

**Pull request closed without merging**
