### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by smorimoto**
[EditorConfig](https://editorconfig.org)

### CODE REVIEW

**Comment by hellcp** [comment]
In HTML and CSS files we got indent of 2 spaces ;)

**Comment by smorimoto** [comment]
Oh! I see.
I found some css and scss files. We also have js files (It has 2 indent and 4 indent). But where is the html file?

**Comment by dansup** [comment]
@imbsky @hellcp It should be 4 spaces. Thanks!

**Comment by smorimoto** [comment]
@dansup Oh, not at all!

**Pull request merged**
