### PR TITLE
Expose RSS syndication feeds on profile page via <link href="..." > tags

### LINKED ISSUE #318: Please expose RSS syndication feeds on profile page via <link href="..." > tags.
eg. \<link href="https://pixelfed.social/users/{username}.atom" rel="alternate" title="{username} on PixelFed" type="application/atom+xml">

### PR DESCRIPTION
**Pull request by lamby**
Closes #318

### CODE REVIEW

**Comment by lamby** [comment]
Gentle ping on this? Seems fairly controversial a change...

**Comment by lamby** [comment]
Gentle ping? :)

**Comment by dansup** [comment]
@lamby Hey, could you resolve the merge conflict and I will merge this! Thanks.

**Comment by lamby** [comment]
@dansup Pushed as 2e7bd00, rebased against `dev` branch.

**Review by dansup — APPROVED** [review]

**Pull request merged**
