### PR TITLE
30 character usernames

### PR DESCRIPTION
**Pull request by MrAn0nym**
Those would be all the changes required to change the username limit to 30 characters. 

Main reason for this change would be feature parity with Instagram but i personally experienced 15 characters being to short as well (issue #3550)

### CODE REVIEW

**Comment by MrAn0nym** [comment]
Any updates?

**Comment by MrAn0nym** [comment]
Delayed until the official release of Metro 2.0

**Comment by dansup** [comment]
Closing for now, as previously discussed this is waiting on Metro v3.

**Comment by McPringle** [comment]
I don't quite understand why this PR was closed. This usually means that it will not be merged. However, I could not find a reason for the rejection. It is mentioned that they are waiting for Metro v3. But that would be waiting and not rejecting. So I am confused about this.

Because I am also interested in adjusting the length of the username to that of Instagram, as I want to move my Instagram account to a Pixelfed instance. Of course, while keeping my username (17 characters), as I am known by it in the community and it cannot be shortened in a meaningful way without changing the meaning. As it is not possible to change usernames at a later date, this point is currently preventing me from migrating.

Since I believe that this is not only the case for me, but also for other Instagram users, an adjustment of the configuration would be very helpful.

Thank you very much for the Pixelfed software, keep up the great work!

**Comment by Sythelux** [comment]
again really bad communication:

it was fixed in this commit: https://github.com/pixelfed/pixelfed/commit/207bb36c89f1ac08f0e62159a01dbd1ee67a356a

**Pull request closed without merging**
