### PR TITLE
Fix: dockerfile libwebp issues

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
See the two individual commits for details; Unfortunately some auto-formatting happened on the dockerfiles so they're a little hard to compare. I've basically removed libwebp7 as a dependency, added wget, enabled the additional database drivers, and changed `apt-get upgrade` to `apt-get dist-upgrade`

Along side this, I took the opportunity to update composer and php to 2.6 and 8.2 respectively. PHP 8.3 isn't compatible with imagick at this time.

### CODE REVIEW

**Comment by andre-dierker** [comment]
I think you missed to update the fpm config to the new php version socket https://github.com/pixelfed/pixelfed/blob/4bb97e1547202365bbd570ce095a0558c77a4d3b/contrib/nginx.conf#L34

**Comment by ThisIsMissEm** [comment]
> I think you missed to update the fpm config to the new php version socket
> 
> https://github.com/pixelfed/pixelfed/blob/4bb97e1547202365bbd570ce095a0558c77a4d3b/contrib/nginx.conf#L34

So I've tried that, I still can't get the server to respond, just get `curl: (56) Recv failure: Connection reset by peer` both from outside and inside the container when trying to curl :9000, which should be the port it's using.

I've tried with both Apache and NGINX-FPM

**Comment by ThisIsMissEm** [comment]
Also the `/contrib/nginx.conf` file doesn't appear to be used by Docker, nor the `/contrib/docker-nginx.conf` file.

**Comment by ThisIsMissEm** [comment]
Okay, I managed to get the Apache one to work, it uses port 80 not 9000 like nginx-fpm (I didn't notice this before)

**Review by x64x2 — APPROVED** [review]

**Comment by Strubbl** [comment]
Just for reference: The imagick with php 8.3 seems to be documented at https://github.com/Imagick/imagick/issues/643

**Review by Strubbl — APPROVED** [review]
Thank you for your patches, i tried them with my setup and the image builds without any issues and the container is running fine.

**Comment by Murazaki** [comment]
Hi, the hadolint linter did not like the usage of `dist-upgrade` , but it seems like [the rule is being deleted](https://github.com/hadolint/hadolint/issues/562). I deactivated it from the Dockerfile linting on my side.

**Comment by Murazaki** [comment]
https://github.com/Murazaki/pixelfed/commits/fix/dockerfile-8.2-fpm-with-nginx -> Contains a nginx stack that works, and I made some cleanup after.
I've seen that @ThisIsMissEm you did the same thing as me in unifying the flavors in github actions in your remote, so I figured the lack of difference between fpm and apache can help us unify a bit more. The cleanup is in a different commit.

**Comment by jippi** [comment]
As I was setting up my own pixelfed server, I ended up reworking the entire Dockerfile setup in my PR here: https://github.com/pixelfed/pixelfed/pull/4844

**Comment by dansup** [comment]
Superseded by #4844

**Pull request closed without merging**
