### PR TITLE
Updating Libwebp6 to libwebp7

### PR DESCRIPTION
**Pull request by Happyfeet01**
Hello,

with one of the latest updates for the instances of Pixelfed the docker-compose build won´t run successful. With this change it works again.

### CODE REVIEW

**Review by HermanRonk — APPROVED** [review]

**Review by x64x2 — APPROVED** [review]

**Comment by dansup** [comment]
Please use the `staging` branch!

**Comment by Happyfeet01** [comment]
Good to know!

**Review by ThisIsMissEm — APPROVED** [review]
@dansup this looks good to me.

**Review by dansup — DISMISSED** [review]

**Comment by Strubbl** [comment]
libwebp7 cannot be found with php:8.1-apache-bullseye.

**Comment by ThisIsMissEm** [comment]
Yes, we're aware. We caught the error shortly after this was merged, but have faced issues fixing it due to having issues testing the docker images.

There is a fix in progress at: https://github.com/pixelfed/pixelfed/pull/4798

We need people to test this out and let us know if it's actually working as expected.

**Comment by Strubbl** [comment]
Maybe we should revert this commit in the dev branch until the fix is finished? At the moment, the docker image fails to build.

**Pull request merged**
