### PR TITLE
Build CI and docker updates for automatic image push to Docker Hub

### PR DESCRIPTION
**Pull request by Murazaki**
Cleaned up branch.
Fork is now delivering images at Murazaki/pixelfed (and automatically rebasing itself, hence the separate branch with different image naming).
I hope you'll find it useful.

### CODE REVIEW

**Comment by dansup** [comment]
@Murazaki Thanks, this should target the `staging` branch!

**Comment by Murazaki** [comment]
@dansup Rebased to staging and pull request updated.

**Comment by harmtemolder** [comment]
There is a whole bunch of open Docker- and Dockerfile-related PRs. It would be great if you could consolidate some of that into your Docker cleanup. I'm willing to jump, if you can use the help

**Comment by Murazaki** [comment]
> There is a whole bunch of open Docker- and Dockerfile-related PRs. It would be great if you could consolidate some of that into your Docker cleanup. I'm willing to jump, if you can use the help

Here you are, could not test the fpm version though but I tried to follow the modifications done. I might need to build fpm separately to have it on docker hub too.

**Comment by Murazaki** [comment]
Apache and FPM updated, see builds here for testing :
https://hub.docker.com/r/murazaki/pixelfed/tags

CI is configured for amd64, arm64 and armv7, if too long, you can maybe ditch armv7 if unused by the community (would mean we can't use it with older 32 bits OS shipped with RPi and other boards)

**Comment by harmtemolder** [comment]
I'm actually not familiar with FPM either

@dansup Do we even need to support FPM, or is it enough to ship with a fully tested and working Apache setup?

**Comment by Murazaki** [comment]
fpm builds and runs, I just didn't bother trying spawning a frontend nginx for it (it's supposed to help have a separate frontend nginx but still asks it to know the path to its own files, which is bothersome when you use nginx as a proxy for your docker web services).

**Comment by Murazaki** [comment]
Not building for armv7 anymore, this should make it less long and resource intensive.

**Review by dansup — APPROVED** [review]

**Comment by Murazaki** [comment]
Thanks @dansup for merging. You might want to create a docker hub pixelfed organization and provide environment variables to point to it in github actions.

**Comment by Murazaki** [comment]
I input my secrets like this, the environment secrets are bit more tricky to use
image

**Pull request merged**
