### PR TITLE
Installer Updated

### PR DESCRIPTION
**Pull request by shleeable**

### CODE REVIEW

**Comment by shleeable** [comment]
TODO: APP_KEY was empty. Confirm that's being processed

**Comment by shleeable** [comment]
Added the validateEnv function to catch empty `APP_KEY`.

**Comment by shleeable** [comment]
Added additional checks for image optimization tools (these are optional and will not exit the installer)

image

**Comment by shleeable** [comment]
Added checks for additional php modules

**Comment by shleeable** [comment]
Added additional PHP modules (these are modules recommended by the installation guide). feel free to switch these around any way
image

**Comment by shleeable** [comment]
I'm going to freeze this PR. Any additional changes will be made after this is merged.

**Comment by shleeable** [comment]
I'm going to freeze this PR. Any additional changes will be made after this is merged.

**Comment by shleeable** [comment]
Updated the PHP Module check and linted the code

image

I'm going to freeze this PR. Any additional changes will be made after this is merged.

**Review by dansup — APPROVED** [review]

**Pull request merged**
