### PR TITLE
[WIP] Docker support with pgsql/sqlite3 and fixed en_US locales.

### PR DESCRIPTION
**Pull request by shleeable**
This passes all (sans .env) of the checks in self-diagnosis.

### CODE REVIEW

**Comment by Shleeble** [comment]
I've tested this configuration with a new setup. and no regressions at least.

This is going to be the first of some additional changes in this space.

**Comment by shleeable** [comment]
DO NOT MERGE YET - Work In Progress

I've tested this configuration with a new setup, and I keep finding problems and fixing them
No regressions at least. ;)

This is going to be the first of some additional changes in this space.

**Comment by shleeable** [comment]
@dansup this is ready to merge, because it fixes a number of bugs - but it is not feature complete.

I am having problems with this, with the new composer breaking.. and as such, unless it's a bug in the code. I'm going to create my own new dockerfile  from scratch and see if I can resolve it in another PR.

**Comment by dansup** [comment]
@Shleeble I invited you to the #pixelfed-dev channel on freenode, we can discuss it there when you have time!

**Review by dansup — APPROVED** [review]

**Pull request merged**
