### PR TITLE
Profile thumb background-image replaced by img

### PR DESCRIPTION
**Pull request by Simounet**
Because this is not decoration but content (and because I'll open an issue about pixel ratio).
I had some issues with npm and not sure about the right dependencies versions so let me know.
I used `object-fit` which is Edge 16+.
Have a nice day.

### CODE REVIEW

**Comment by dansup** [comment]
@Simounet Pixelfed uses a webpack wrapper called Mix, please follow [these instructions](https://laravel.com/docs/5.6/mix#running-mix) to compile the assets.

**Comment by Simounet** [comment]
I did it and rebased my branch.

**Comment by Simounet** [comment]
Branch rebased and now pointing to `dev`.

**Comment by dansup** [comment]
Profiles are now loaded via a vue component which uses ``````

**Pull request closed without merging**
